ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DEPARTMENT_HEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CLASS_COORDINATOR';

ALTER TABLE "profiles"
ADD COLUMN IF NOT EXISTS "handle" TEXT,
ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS "profiles_handle_key" ON "profiles"("handle");
